#Hugo configuration
title = "dfh"
baseURL = "https:\/\/www.googe.com"
languageCode = "en-us"
theme = "tvpage"
disablePathToLower = "true"
enableRobotsTXT = true

[params]
loginId = "1758397"
subfolder = ""
